import { adobeLogo, tokopediaLogo, travelokaLogo } from "./images";

export const jobsList = [
  {
    id: "1",
    companyIcon: adobeLogo,
    jobTitle: "UI/UX Designer",
    company: "Adobe CC",
    location: "Blessen George",
    desc: "Match with your profile",
    tags: ["Full Time", "Hybrid", "2.4 Years"],
    days: 3,
    applicants: 240,
    salary: 3000,
  },
  {
    id: "2",
    companyIcon: travelokaLogo,
    jobTitle: "Product Designer",
    company: "Traveloka",
    location: "Jakarta, Indonesia",
    desc: "Match with your profile",
    tags: ["Full time", "Onsite", "2-4 Years"],
    days: 1,
    applicants: 140,
    salary: 1500,
  },
  {
    id: "3",
    companyIcon: tokopediaLogo,
    jobTitle: "UX Designer",
    company: "Tokopedia",
    location: "Jakarta, Indonesia",
    desc: "Match with your profile",
    tags: ["Full Time", "Remote", "2.4 Years"],
    days: 2,
    applicants: 90,
    salary: 2000,
  },
  {
    id: "4",
    companyIcon: adobeLogo,
    jobTitle: "UI/UX Designer",
    company: "Adobe CC",
    location: "Blessen George",
    desc: "Match with your profile",
    tags: ["Full Time", "Hybrid", "2.4 Years"],
    days: 3,
    applicants: 240,
    salary: 3000,
  },
  {
    id: "1",
    companyIcon: adobeLogo,
    jobTitle: "UI/UX Designer",
    company: "Adobe CC",
    location: "Blessen George",
    desc: "Match with your profile",
    tags: ["Full Time", "Hybrid", "2.4 Years"],
    days: 3,
    applicants: 240,
    salary: 3000,
  },
  {
    id: "2",
    companyIcon: adobeLogo,
    jobTitle: "UI/UX Designer",
    company: "Adobe CC",
    location: "Blessen George",
    desc: "Match with your profile",
    tags: ["Full Time", "Hybrid", "2.4 Years"],
    days: 3,
    applicants: 240,
    salary: 3000,
  },
  {
    id: "3",
    companyIcon: adobeLogo,
    jobTitle: "UI/UX Designer",
    company: "Adobe CC",
    location: "Blessen George",
    desc: "Match with your profile",
    tags: ["Full Time", "Hybrid", "2.4 Years"],
    days: 3,
    applicants: 240,
    salary: 3000,
  },
  {
    id: "4",
    companyIcon: adobeLogo,
    jobTitle: "UI/UX Designer",
    company: "Adobe CC",
    location: "Blessen George",
    desc: "Match with your profile",
    tags: ["Full Time", "Hybrid", "2.4 Years"],
    days: 3,
    applicants: 240,
    salary: 3000,
  },
  {
    id: "1",
    companyIcon: adobeLogo,
    jobTitle: "UI/UX Designer",
    company: "Adobe CC",
    location: "Blessen George",
    desc: "Match with your profile",
    tags: ["Full Time", "Hybrid", "2.4 Years"],
    days: 3,
    applicants: 240,
    salary: 3000,
  },
  {
    id: "2",
    companyIcon: adobeLogo,
    jobTitle: "UI/UX Designer",
    company: "Adobe CC",
    location: "Blessen George",
    desc: "Match with your profile",
    tags: ["Full Time", "Hybrid", "2.4 Years"],
    days: 3,
    applicants: 240,
    salary: 3000,
  },
  {
    id: "3",
    companyIcon: adobeLogo,
    jobTitle: "UI/UX Designer",
    company: "Adobe CC",
    location: "Blessen George",
    desc: "Match with your profile",
    tags: ["Full Time", "Hybrid", "2.4 Years"],
    days: 3,
    applicants: 240,
    salary: 3000,
  },
  {
    id: "4",
    companyIcon: adobeLogo,
    jobTitle: "UI/UX Designer",
    company: "Adobe CC",
    location: "Blessen George",
    desc: "Match with your profile",
    tags: ["Full Time", "Hybrid", "2.4 Years"],
    days: 3,
    applicants: 240,
    salary: 3000,
  },
];
